version: "3"
services:
  mysql:
    image: mysql:8.0
    hostname: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Seoul
    ports:
      - "3326:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      # - ./mysqlinit/mysql-init.sql:/docker-entrypoint-initdb.d/init.sql
      # 초기 DB 세팅 mysql -uroot -p --port 3306 < data_setting.sql
      # - ./mysql-init-files/:/docker-entrypoint-initdb.d
    networks:
      - kraft_kafka_network
  connect:
    image: confluentinc/cp-kafka-connect:7.6.1
    hostname: connect
    ports:
      - "8083:8083"
    environment:
      CONNECT_BOOTSTRAP_SERVERS: broker:29092
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: "connect-cluster"
      CONNECT_CONFIG_STORAGE_TOPIC: "connect-configs"
      CONNECT_OFFSET_STORAGE_TOPIC: "connect-offsets"
      CONNECT_STATUS_STORAGE_TOPIC: "connect-status"
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_REST_ADVERTISED_HOST_NAME: "localhost"
      CONNECT_LOG4J_ROOT_LOGLEVEL: INFO
      CONNECT_PLUGIN_PATH: "/usr/share/java,/usr/share/confluent-hub-components,/etc/kafka-connect/jars"
      # CONNECT_JDBC_DRIVER_CLASS: "com.mysql.jdbc.Driver"
    volumes:
      - ./plugins:/etc/kafka-connect/jars
    networks:
      - kraft_kafka_network
volumes:
  mysql-data:

networks:
  kraft_kafka_network:
    external: true
